import { Button, ButtonGroup, Grid, TextField, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import QrCodeScanner from '@components/qr-code-scanner/QrCodeScanner'
import DeviceRegistration from '@modules/device-registration/DeviceRegistration'
import MenuDrawer from '@modules/menu-drawer/MenuDrawer'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <DeviceRegistration/> */}
       {/*  <ButtonGroup variant="outlined" aria-label="outlined button group">
            <Button>One</Button>
            <Button>Two</Button>
            <Button>Three</Button>
        </ButtonGroup> */}
        <MenuDrawer/>
      </main>
    </div>
  )

  
}

export default Home
