import { TextField } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'

const qrcodeRegionId = "html5qr-code-full-region";
import styles from '../styles/Home.module.css'
import Html5QrcodePlugin from '@components/QrCodeScanner'
import QrCodeScanner from '@components/QrCodeScanner'

const Home: NextPage = () => {
  const [devEUI, setDevEUI] = useState("")
  const onNewScanResult = (props:any)  => {
    setDevEUI(props)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>Skriv saker</h2>
        {/* <TextField id='outlined-basic' label="Outlined" variant='outlined'/> */}
        <TextField id='name' label="Name" color="secondary" focused />
        <TextField id='dev_eui' label="Dev EUI" color="secondary" focused value={devEUI}/>
        <TextField id="app_eui" label="App EUI" color="secondary" focused />
        <TextField id="app_key" label="App Key" color="secondary" focused />
        <QrCodeScanner
            config={{
              fps: 10,
              qrbox: 250,
              disableFlip: false
            }}
            successCallback={onNewScanResult}
          />
      </main>
    </div>
  )
}

/* const Test = (props:any) => {
  const [result, setResult] = useState("yeye");
  const onNewScanResult = (props:any)  => {
    setResult(props)
  }

  return (
    <>
     <h1>Html5Qrcode React example!</h1>
          
    <p>{result}</p>
    </>
  );
}; */

export default Home
